on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependency
        run: yarn install

      - name: Lint & Format
        run: |
          npm run lint
          npm run format
